//! Build-time generation of the bundled skin list.
//!
//! Scans the workspace `skins/` directory for `*.wsz` files and emits a
//! Rust source file (`bundled_skins.rs`) that the desktop binary
//! `include!`s. Each skin becomes a `BundledSkin { name, bytes }` entry
//! whose `bytes` is filled by `include_bytes!`, so the .wsz contents are
//! linked straight into the executable.
//!
//! Touching `skins/` invalidates the build; adding a new `.wsz` is a
//! drop-and-rebuild operation with no source edit required.

use std::fs;
use std::path::PathBuf;

fn main() {
    // Locate the workspace `skins/` directory from CARGO_MANIFEST_DIR
    // (oneamp-desktop). `..` climbs up to the workspace root.
    let manifest_dir = PathBuf::from(
        std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is set by cargo"),
    );
    let skins_dir = manifest_dir
        .parent()
        .expect("oneamp-desktop sits inside the workspace")
        .join("skins");

    // Rerun whenever skins/ contents change.
    println!("cargo:rerun-if-changed={}", skins_dir.display());

    let mut entries: Vec<PathBuf> = match fs::read_dir(&skins_dir) {
        Ok(read) => read
            .filter_map(|e| e.ok())
            .map(|e| e.path())
            .filter(|p| {
                p.extension()
                    .and_then(|x| x.to_str())
                    .map(|x| x.eq_ignore_ascii_case("wsz"))
                    .unwrap_or(false)
            })
            .collect(),
        Err(_) => Vec::new(),
    };
    entries.sort();

    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by oneamp-desktop/build.rs — do not edit by hand.\n");
    out.push_str("pub struct BundledSkin {\n");
    out.push_str("    pub name: &'static str,\n");
    out.push_str("    pub bytes: &'static [u8],\n");
    out.push_str("}\n\n");
    out.push_str("pub const BUNDLED_SKINS: &[BundledSkin] = &[\n");
    for entry in &entries {
        let name = entry
            .file_stem()
            .and_then(|n| n.to_str())
            .unwrap_or("Unknown")
            .to_string();
        let abs = entry.to_string_lossy().to_string();
        // Forward slashes work in include_bytes! on Windows too.
        let abs_norm = abs.replace('\\', "/");
        out.push_str(&format!(
            "    BundledSkin {{ name: {:?}, bytes: include_bytes!({:?}) }},\n",
            name, abs_norm
        ));
    }
    out.push_str("];\n");

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR is set by cargo"));
    let dest = out_dir.join("bundled_skins.rs");
    fs::write(&dest, out).expect("failed to write bundled_skins.rs");

    // ── Build-info env vars surfaced in the About dialog ──────────────
    //
    // `ONEAMP_GIT_HASH` — short commit hash if we're building inside a
    // git checkout; empty when building from a tarball release (the
    // dist artefacts ship without `.git/`). Empty is the sentinel the
    // About handler checks against, so it can fall back gracefully.
    //
    // `ONEAMP_BUILD_DATE` — ISO-8601 calendar date at build time. Pure
    // calendar date, no time / timezone — bug reporters care about
    // "what week of which year was this binary cut" not "down to the
    // second". Filled from `SOURCE_DATE_EPOCH` when set so distro
    // packagers' reproducible builds stay reproducible.
    let git_hash = std::process::Command::new("git")
        .args(["rev-parse", "--short", "HEAD"])
        .output()
        .ok()
        .filter(|o| o.status.success())
        .and_then(|o| String::from_utf8(o.stdout).ok())
        .map(|s| s.trim().to_string())
        .unwrap_or_default();
    println!("cargo:rustc-env=ONEAMP_GIT_HASH={}", git_hash);

    let build_epoch = std::env::var("SOURCE_DATE_EPOCH")
        .ok()
        .and_then(|s| s.parse::<u64>().ok())
        .unwrap_or_else(|| {
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .map(|d| d.as_secs())
                .unwrap_or(0)
        });
    let build_date = epoch_to_iso_date(build_epoch);
    println!("cargo:rustc-env=ONEAMP_BUILD_DATE={}", build_date);
    // Re-run the build script when HEAD moves so the hash stays
    // current. The skin re-run directive above already covers skin
    // changes.
    println!("cargo:rerun-if-changed=../.git/HEAD");
    println!("cargo:rerun-if-env-changed=SOURCE_DATE_EPOCH");
}

/// Convert a Unix epoch in seconds to a `YYYY-MM-DD` calendar date,
/// using the proleptic Gregorian calendar. Local timezone is ignored —
/// we publish UTC dates so distro reproducible builds match
/// `SOURCE_DATE_EPOCH` exactly.
fn epoch_to_iso_date(epoch: u64) -> String {
    let days = (epoch / 86_400) as i64;
    // Howard Hinnant's "days from civil" inverse, reused under public
    // domain. Returns `(year, month, day)` for the Gregorian date at
    // `days` since 1970-01-01.
    let days = days + 719_468;
    let era = days.div_euclid(146_097);
    let doe = days.rem_euclid(146_097);
    let yoe = (doe - doe / 1460 + doe / 36_524 - doe / 146_096) / 365;
    let y = yoe + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = doy - (153 * mp + 2) / 5 + 1;
    let m = if mp < 10 { mp + 3 } else { mp - 9 };
    let y = if m <= 2 { y + 1 } else { y };
    format!("{:04}-{:02}-{:02}", y, m, d)
}
